[site]
title = "Antora Demo Site"
url = "https://antora.gitlab.io/demo/docs-site"
start_page = "component-b::index.adoc"

[[content.sources]]
url = "https://github.com/alliander-opensource/metamorph.git"
branches = ["feature/refactor"]
start_path = "docs"

[asciidoc.attributes]
experimental = ""
idprefix = ""
idseparator = "-"
page-pagination = ""

[ui.bundle]
url = "https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable"
snapshot = true

[output]
dir = "./docs"