# SPDX-FileCopyrightText: 2022 Alliander N.V.
#
# SPDX-License-Identifier: Apache-2.0

name: Compile and Release GraalVM Native Images
run-name: ${{ github.actor }} is compiling GraalVM Native Images
on:
  push:
    branches:
      - "73-automated-build-executables"
jobs:
  build-binary:
    name: 'Build binary on ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: Setup GraalVM & Java
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@11.0
        with:
          lein: 2.9.10

      - name: Build MetaMorph
        run: |
          lein native-image
